# Database Configuration
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/calendar?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.username=root
db.password=Anhvu02052004@

# Logging
logging.level.org.springframework=INFO
logging.level.com.schedulemanager=DEBUG